---
title: "Activities from Week 10, Lecture 1: Data Ethics"
subtitle: "SDS 192: Introduction to Data Science"
author: "Zully Luna Romero"
---

## Introduction

We've discussed some ideas regarding data ethics. With those around you, you will discuss your thoughts on the video and answer questions regarding two different articles.

## Carissa Véliz: How privacy can save your life

You've just watched a TEDTalk from Carissa Véliz about how data privacy should be used to protect your livelihood. You can access the video for reference [here](https://www.youtube.com/watch?v=xSPRouBvgFE).

After talking to others about the video, answer the following questions below:

::: {.callout-important}
###### Q1

What are some important ideas that Carissa Véliz talked about in the video? What are your thoughts to some of the examples she used and her perspective?

- choose which kind of data you want to be out there and choose in which situation it would be helpful for other pieces of data to be out there
- with the example about the book and electronic book, it made us rethink about how our data is being used and why people would want to use our data to the point where we should care more
:::

## Your data is diminishing your freedom

Read the New York Times article "Your Data is Diminishing Your Freedom" at the following link [here](https://www.nytimes.com/interactive/2023/03/20/magazine/colin-koopman-interview.html). After discussing your thoughts on the piece, answer the following questions:

::: {.callout-important}
###### Q2

What does it mean that "we have become our own data?" How does that sentiment affect your personal decision-making, and how we define ourselves?

- the phrase "we have become our own data" means that we are what is on record of us to the government or other people accessing our data; we are nothing more
- in a way, data is not personal because it can't describe how we are as people but other people looking at our data could make assumptions about we are as people- even if it may be a lie. 

:::

::: {.callout-important}
###### Q3

Using the article as support, what are some concerns you personally have about the use of your data? 

- it makes me concerned about how certain websites are using my data and why they need certain agreements for me to follow which would allow them to have access to my data. it makes me think of when logging onto a website using your google account, it kind of forces you to give them access to your information because if you don't, you don't have access to what they offer. 
- there are just certain things where you don't have a choice in how you want people to use your data; in a way, you're just forced to comply. 

:::

## Federal Data Strategy

The U.S. Government has a Federal Data Strategy with the hopes of defining how to use data to serve the public and steward resources while "protecting security, privacy, and confidentiality."

You will read page 4 of the Data Ethics Framework based on the strategy [here](https://resources.data.gov/assets/documents/fds-data-ethics-framework.pdf). After discussing your thoughts on the piece, answer the following questions:


::: {.callout-important}
###### Q4

Discuss examples about how a government (or smaller body) could execute a data ethics tenet of your choice.

- for the 7th data ethics tenet, I would say the government or smaller body could find a more clearer way of telling the public of new advancements/developments in this field. I say this because for certain apps, they have implimented different things that would allow them to have access to mroe of our data than before and most people are unaware of that because it is said in the tiny print. Not many people read it in the first place because there is a lot of information so it would be helpful if they could summarize it in a few key points. 
:::

## Turn-in

Save the .qmd file inside your activities repository. Please stage, commit, and push to GitHub.